# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "81636ad2f90c992ce61d37e260c77da6"
name = "finalstock"
handle = "finalstock-1"
application_url = "https://rooms-distant-impossible-revolutionary.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders-create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products"

[auth]
redirect_urls = [
  "https://rooms-distant-impossible-revolutionary.trycloudflare.com/auth/callback",
  "https://rooms-distant-impossible-revolutionary.trycloudflare.com/auth/shopify/callback",
  "https://rooms-distant-impossible-revolutionary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
